### ISSUE TITLE
Installation failed with rake syntax error

### ISSUE THREAD

**Issue by pscholze** [luismaia/redmine_email_fetcher#1]
After executing step 3 of installation procedure:
```
rake redmine:plugins:migrate RAILS_ENV=production
```
I got following error:
```
rake aborted!
/usr/local/share/redmine-2.5.2/plugins/redmine_email_fetcher/lib/tasks/email_fetcher.rake:14: syntax error, unexpected ':', expecting kEND
      task 'fetch_all_emails': :environment do |t, args|
                              ^
/usr/local/share/redmine-2.5.2/plugins/redmine_email_fetcher/lib/tasks/email_fetcher.rake:14: syntax error, unexpected '|', expecting '='
/usr/local/share/redmine-2.5.2/plugins/redmine_email_fetcher/lib/tasks/email_fetcher.rake:20: syntax error, unexpected kEND, expecting $end
/var/lib/gems/1.8/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.8/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.8/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.8/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.8/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.8/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.8/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/var/lib/gems/1.8/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/var/lib/gems/1.8/gems/railties-3.2.19/lib/rails/engine.rb:425:in `load_tasks'
/var/lib/gems/1.8/gems/railties-3.2.19/lib/rails/engine.rb:425:in `each'
/var/lib/gems/1.8/gems/railties-3.2.19/lib/rails/engine.rb:425:in `load_tasks'
/var/lib/gems/1.8/gems/railties-3.2.19/lib/rails/application.rb:145:in `load_tasks'
/var/lib/gems/1.8/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `send'
/var/lib/gems/1.8/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
```

**Comment by luismaia** [comment]
This issue looks to be related with the use of a Ruby 1.8 version (this version is out of support - https://www.ruby-lang.org/en/news/2014/07/01/eol-for-1-8-7-and-1-9-2/).

@pscholze - Could you test if using a version equal or higher than 1.9.3 the issue disappears?

Thanks.
