### ISSUE TITLE
Problems with more than one email configuration with pop3

### ISSUE THREAD

**Issue by anjo256** [luismaia/redmine_email_fetcher#10]
I tried to set up three different email configurations with pop3. All configurations contain the same host but different user names. 
While the first one works pretty well, the two new ones behave strangely: The messages of the two new accounts don't get deleted nor marked as read. Therefore, every time the messages are fetched I get the "old" emails as new tickets.
Do you know what's going wrong?

**Comment by luismaia** [comment]
@anjo256 sorry for the later reply, but unfortunately I was on vacations without computer.
I will try to reproduce this and give you feedback till the beginning of the next week.

In the meanwhile, could you please let me know:
- what is your redmine_email_fetcher version
- what happens if you manually (in the administration page) fetch the email configuration which emails don't get deleted nor marked as read. Does the same behavior continues?

Additionally, could you also provide me your 3 email configurations information (except the passwords):
- To get all email configurations information, just go to your Redmine application folder using the terminal and execute: **`rails console`**
- And then inside the rails console (to get the output I need) execute:
  **`EmailConfiguration.all`** (don't forget to remove the password information)

Thanks a lot for your issue and additional information!

**Comment by anjo256** [comment]
No problem! Thank you very much for your efforts!

My redmine_email_fetcher version: 0.3.1 along with redmine_helpdesk 0.0.12 (Redmine version 2.5.3.stable.14155)

What happens if I manually fetch the email configuration:
There is always just one/ the same old email which is fetched. Any new won't get fetched plus i get the following error:

Started GET "/admin/email_configurations/3/fetch" for 89.26.37.241 at 2015-06-03 09:38:34 +0200
Processing by EmailConfigurationsController#fetch as HTML
  Parameters: {"id"=>"3"}
  Current user: admin (id=1)
  Rendered mailer/_issue.text.erb (1.7ms)
  Rendered mailer/issue_add.text.erb within layouts/mailer (2.4ms)
  Rendered mailer/_issue.html.erb (1.1ms)
  Rendered mailer/issue_add.html.erb within layouts/mailer (1.5ms)
Started GET "/issues/259" for 95.143.162.114 at 2015-06-03 09:38:35 +0200
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"259"}
  Current user: X (id=3)
  Rendered common/error.html.erb within layouts/base (1.0ms)
Saving attachment '/opt/redmine/current/files/2015/06/150603093835_image001.jpg' (3348 bytes)
MailHandler: issue #263 created by X X
  Rendered mailer/issue_edit.html.erb (1.5ms)
Completed 500 Internal Server Error in 1797.2ms

ActionView::Template::Error (undefined method `private_notes?' for nil:NilClass):
    1: <% if @journal.private_notes? %>
    2:   (<%= l(:field_private_notes) %>)
    3: <% end %>
    4: <%= l(:text_issue_updated, :id => "##{@issue.id}", :author => h(@journal.user)) %>
  app/views/mailer/issue_edit.html.erb:1:in`_app_views_mailer_issue_edit_html_erb___1118356321288002952_70086665023160'
  app/models/mail_handler.rb:159:in `dispatch'
  app/models/mail_handler.rb:134:in`receive'
  app/models/mail_handler.rb:46:in `receive'
  lib/redmine/pop3.rb:39:in`block (2 levels) in check'
  lib/redmine/pop3.rb:36:in `block in check'
  lib/redmine/pop3.rb:31:in`check'

 This error occurs only if I fetch the emails manually.

 For the second part I'd like to send you a private message...
