### ISSUE TITLE
Plugin not working.

### ISSUE THREAD

**Issue by amit-mitra** [luismaia/redmine_email_fetcher#17]
Http Error on clicking Administration -> Fetch Email

ActionView::Template::Error (Mysql2::Error: Table 'bitnami_redmine.email_configurations' doesn't exist: SELECT `email_configurations`.\* FROM `email_configurations`):
    26:     </tr>
    27:     </thead>
    28: 
    29:     <% @email_configurations.each do |config| %>
    30:         <tr id="email-config-<%= config.id %>">
    31:           <td align="center"><%= config.configuration_type.upcase %></td>
    32:           <td align="center"><%= config.host %></td>
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Installation output : 

C:\Bitnami\redmine-3.1.0-0\apps\redmine\htdocs>rake redmine:plugins:migrate RAIL
S_ENV=production --trace
DL is deprecated, please use Fiddle
*\* Invoke redmine:plugins:migrate (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute redmine:plugins:migrate
Migrating redmine_agile (Redmine Agile plugin (Light version))...
== 3 RenameIssueStatusOrders: migrating =======================================
-- rename_table(:issue_status_orders, :agile_ranks)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Table 'agile_ranks' already exists: RENAME TABLE `issue_status_or
ders` TO `agile_ranks`C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/a
ctiverecord-4.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.r
b:305:in `query'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/connection_adapters/abstract_mysql_adapter.rb:305:in`block in exe
cute'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activesupport-4.2.3/lib
/active_support/notifications/instrumenter.rb:20:in`instrument'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/connection_adapters/abstract_adapter.rb:467:in `log'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/connection_adapters/abstract_mysql_adapter.rb:305:in`execute'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/connection_adapters/abstract_mysql_adapter.rb:491:in`rename_table
'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:661:in `block in method_missing'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:631:in`block in say_with_time'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:631:in`say_with_time'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:651:in `method_missing'
C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/plugins/redmine_agile/db/migrate/
003_rename_issue_status_orders.rb:22:in`change'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:605:in `exec_migration'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:589:in`block (2 levels) in migrate'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/2.0.0/benchmark.rb:281:in `measure'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:588:in`block in migrate'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_conne
ction'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:587:in`migrate'
C:in `migrate'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:994:in`block in execute_migration_in_transaction'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:1042:in `ddl_transaction'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:993:in`execute_migration_in_transaction'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:955:in `block in migrate'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:951:in`each'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:951:in `migrate'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:819:in`up'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/activerecord-4.2.3/lib/
active_record/migration.rb:797:in `migrate'
C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:481:in`mig
rate_plugin'
C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:453:in `mig
rate'
C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:467:in`blo
ck in migrate'
C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:466:in `eac
h'
C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/lib/redmine/plugin.rb:466:in`mig
rate'
C:/Bitnami/redmine-3.1.0-0/apps/redmine/htdocs/lib/tasks/redmine.rake:127:in `bl
ock (3 levels) in <top (required)>'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:240:in`call'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:240:in `block in execute'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:235:in`each'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:235:in `execute'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:179:in`block in invoke_with_call_chain'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchroniz
e'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:172:in`invoke_with_call_chain'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ta
sk.rb:165:in `invoke'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:150:in`invoke_task'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:106:in `block (2 levels) in top_level'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:106:in`each'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:106:in `block in top_level'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:115:in`run_with_threads'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:100:in `top_level'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:78:in`block in run'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:176:in `standard_exception_handling'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/ap
plication.rb:75:in`run'
C:/Bitnami/redmine-3.1.0-0/ruby/lib/ruby/gems/2.0.0/gems/rake-10.4.2/bin/rake:33
:in `<top (required)>'
C:/Bitnami/redmine-3.1.0-0/ruby/bin/rake:23:in`load'
C:/Bitnami/redmine-3.1.0-0/ruby/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate

I'm using redmine using the Bitnami stack.

**Comment by amit-mitra** [comment]
Ok , i could install it . but now its giving SSL error

**Comment by aceccarelli** [comment]
Hi,

In my Redmine presents this error also

Tks

<pre>
Completed 500 Internal Server Error in 333ms (ActiveRecord: 2.2ms)
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=unknown state: unknown protocol):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
 </pre>

**Comment by octoquad** [comment]
Hi,

I know this issue is old, but this doesn't look like the issue is caused by this plugin.

Please consider closing this issue if you managed to get this plugin working.

Thanks
