### ISSUE TITLE
SSL Issue with cert

### ISSUE THREAD

**Issue by nixmomo** [luismaia/redmine_email_fetcher#29]
Hi,

how can i disable the certificate verify for ssl servers?

My cert works well and there is no issue but the Plugin won't this cert from one of my Servers...

```
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed):
  plugins/redmine_email_fetcher/app/models/email_tests.rb:22:in `new'
  plugins/redmine_email_fetcher/app/models/email_tests.rb:22:in `block in test_imap'
  plugins/redmine_email_fetcher/app/models/email_tests.rb:21:in `test_imap'
  plugins/redmine_email_fetcher/app/models/email_tests.rb:9:in `test'
  plugins/redmine_email_fetcher/app/controllers/email_configurations_controller.rb:112:in `test'
```

Thanks for a quick reply

Regards

**Comment by nixmomo** [comment]
so what... deinstalled
