### ISSUE TITLE
Email fetcher add configuration issue

### ISSUE THREAD

**Issue by kailashr2k3** [luismaia/redmine_email_fetcher#31]
I am getting the following error in the portal when I try to add a configuration. The error message says that to check the log, but don't know which log to check. Can help advice on this below error message?

_Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error._

**Comment by kailashr2k3** [comment]
**More information from the log**

Completed 500 Internal Server Error in 14ms (ActiveRecord: 5.5ms)

ActionView::Template::Error (undefined method `humanize' for nil:NilClass):
    12:         <p><%= f.select :flg_active, [['True', 'true'], ['False', 'false']],
    13:                         { label: l(:field_flg_active), required: true } %> </p>
    14:
    15:         <p>
    16:           <%= f.label '', { label: l(:field_last_fetch_at) } %>
    17:           <%- if @email_configuration.last_fetch_at.nil? %>
    18:               <%= '---' %>
  config/initializers/10-patches.rb:18:in `human_attribute_name'
  plugins/redmine_email_fetcher/app/views/email_configurations/_form.html.erb:15:in `block in _plugins_redmine_email_f$
  app/helpers/application_helper.rb:1051:in `labelled_form_for'
  plugins/redmine_email_fetcher/app/views/email_configurations/_form.html.erb:1:in `_plugins_redmine_email_fetcher_app$
  plugins/redmine_email_fetcher/app/views/email_configurations/new.html.erb:3:in `_plugins_redmine_email_fetcher_app_v$
  plugins/redmine_email_fetcher/app/controllers/email_configurations_controller.rb:32:in `new'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by TyRoden** [comment]
I am getting the same error. Compatibility with the current version perhaps?

**Comment by zealsara** [comment]
hi am getting the same error.. what is the solution

**Comment by jorv83** [comment]
See my comment in #32

**Comment by octoquad** [comment]
A fix is available in #33 and I have requested that a PR be created at https://github.com/octoquad/redmine_email_fetcher instead.
