### ISSUE TITLE
email_fetcher task throws error

### ISSUE THREAD

**Issue by saz** [luismaia/redmine_email_fetcher#4]
I'm seeing the following error

```
rake aborted!
NoMethodError: undefined method `trace' for #<Class:0x000000072b2508>
/var/www/.gem/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/dynamic_matchers.rb:55:in `method_missing'
/usr/share/redmine/plugins/redmine_email_fetcher/app/models/email_configuration.rb:48:in `block in fetch_all_emails'
/var/www/.gem/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/relation/delegation.rb:6:in `each'
/var/www/.gem/ruby/2.0.0/gems/activerecord-3.2.21/lib/active_record/relation/delegation.rb:6:in `each'
/usr/share/redmine/plugins/redmine_email_fetcher/app/models/email_configuration.rb:43:in `fetch_all_emails'
/usr/share/redmine/plugins/redmine_email_fetcher/lib/tasks/email_fetcher.rake:15:in `block (4 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:email_fetcher:fetch_all_emails
(See full trace by running task with --trace)
```

Any idea, how to fix this?

**Comment by luismaia** [comment]
@saz - Could you please test and let me know if the current trunk solves your issue.
Thanks a lot!

**Comment by luismaia** [comment]
Closed, since it was tested by Andreas on issue #6 .
Either way, let me know if your issue is now solved.
Thanks.
